version: "3.8"

services:
  web:
    image: diamol/ch06-todo-list
    ports:
      - "80:80"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_DB: todo_db
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
    driver: local
